"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState, type ReactNode } from "react";
import { Activity, Bell, CalendarDays, ChevronDown, ClipboardList, LayoutDashboard, Menu, Settings, Users, X, Stethoscope, Clock3, UserRoundCog } from "lucide-react";
import { ToastHost } from "@/components/ui";
import { createSupabaseBrowserClient, demoMode } from "@/lib/supabase";
import { getData, loadData, setCurrentUser, useClinicData } from "@/lib/store";
import { loadClinicDataFromSupabase } from "@/services/data";
import type { CurrentUser } from "@/types";
const receptionistLinks=[{href:"/reception/dashboard",label:"Dashboard",icon:LayoutDashboard},{href:"/appointments",label:"Appointments",icon:CalendarDays},{href:"/reception/queue",label:"Check-in queue",icon:Clock3},{href:"/patients",label:"Patients",icon:Users},{href:"/reception/doctors",label:"Doctor schedules",icon:Stethoscope},{href:"/follow-ups",label:"Follow-ups",icon:ClipboardList},{href:"/missed",label:"Missed & recovery",icon:Activity},{href:"/reception/reminders",label:"Reminder preview",icon:Bell}];
const doctorLinks=[{href:"/doctor/dashboard",label:"Dashboard",icon:LayoutDashboard},{href:"/doctor/schedule",label:"My Schedule",icon:CalendarDays},{href:"/patients",label:"Patients",icon:Users},{href:"/follow-ups",label:"Follow-ups",icon:ClipboardList},{href:"/missed",label:"Missed appointments",icon:Activity},{href:"/doctor/availability",label:"Availability",icon:Clock3},{href:"/doctor/team",label:"Team",icon:UserRoundCog},{href:"/settings",label:"Settings",icon:Settings}];
export function AppShell({children}:{children:ReactNode}){
 const path=usePathname();const router=useRouter();const data=useClinicData();const [open,setOpen]=useState(false);const [ready,setReady]=useState(false);const user=data.currentUser;const links=user?.role==="doctor"?doctorLinks:receptionistLinks;
 useEffect(()=>{let live=true;const check=async()=>{const kind=localStorage.getItem("clinicflow-session");if(kind==="demo"&&demoMode){let current:CurrentUser|undefined;try{const raw=localStorage.getItem("clinicflow-user");if(raw)current=JSON.parse(raw) as CurrentUser}catch{}if(live){setCurrentUser(current??getData().currentUser??{id:"staff-reception-1",full_name:"Riya Sharma",email:"reception@clinicflow.demo",role:"receptionist"});setReady(true)}return}if(kind==="supabase"){try{const client=createSupabaseBrowserClient();const {data:{session}}=await client.auth.getSession();if(session){const result=await loadClinicDataFromSupabase();if(live){loadData(result.data,result.clinicId);setReady(true)}return}}catch(error){if(live)window.dispatchEvent(new CustomEvent("clinicflow:toast",{detail:error instanceof Error?error.message:"Unable to load clinic data"}))}}localStorage.removeItem("clinicflow-session");router.replace("/login")};void check();return()=>{live=false}},[router]);
 useEffect(()=>{if(!ready||!user)return;if(path==="/dashboard"){router.replace(user.role==="doctor"?"/doctor/dashboard":"/reception/dashboard");return}if(user.role==="doctor"&&path.startsWith("/reception/"))router.replace("/doctor/dashboard");if(user.role==="receptionist"&&(path.startsWith("/doctor/")||path==="/settings"))router.replace("/reception/dashboard")},[path,ready,router,user]);
 useEffect(()=>{if(!ready||!user)return;let timer:number;const timeout=20*60*1000;const reset=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{if(localStorage.getItem("clinicflow-session")==="supabase"){try{void createSupabaseBrowserClient().auth.signOut()}catch{}}localStorage.removeItem("clinicflow-session");localStorage.removeItem("clinicflow-user");setCurrentUser(undefined);router.replace("/login")},timeout)};const events=["pointerdown","keydown","touchstart"];events.forEach(event=>window.addEventListener(event,reset,{passive:true}));reset();return()=>{window.clearTimeout(timer);events.forEach(event=>window.removeEventListener(event,reset))}},[ready,router,user]);
 const signOut=async()=>{if(localStorage.getItem("clinicflow-session")==="supabase"){try{const client=createSupabaseBrowserClient();await client.auth.signOut()}catch{}}localStorage.removeItem("clinicflow-session");localStorage.removeItem("clinicflow-user");setCurrentUser(undefined);router.replace("/login")};
 if(!ready)return <div style={{minHeight:"100vh",background:"#f7f9f7"}}/>;
 return <div className="shell"><aside className={`sidebar ${open?"open":""}`}><Link href={user?.role==="doctor"?"/doctor/dashboard":"/reception/dashboard"} className="brand"><span className="brand-mark"><Activity size={19}/></span><span>clinicflow</span></Link><div className="nav-label">{user?.role==="doctor"?"DOCTOR WORKSPACE":"FRONT DESK"}</div><nav className="nav-list">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setOpen(false)} className={`nav-link ${path===href||path.startsWith(href+"/")?"active":""}`}><Icon size={17}/>{label}</Link>)}</nav><div className="sidebar-bottom"><div className="demo-note"><strong style={{color:"#547564"}}>{demoMode?"Demo workspace":"Connected workspace"}</strong><br/>{demoMode?"Fictional records are stored in this browser only.":"Clinic records are synced with Supabase."}</div><div className="user-chip"><div className="avatar">{user?.full_name.split(" ").map(p=>p[0]).slice(0,2).join("")??"CF"}</div><div><div className="user-name">{user?.full_name??"Clinic staff"}</div><div className="user-role">{user?.role=== "doctor"?"Doctor":"Receptionist"}</div></div><button className="btn btn-quiet btn-sm" style={{marginLeft:"auto"}} onClick={signOut} aria-label="Sign out"><ChevronDown size={15}/></button></div></div></aside><main className="main"><header className="topbar"><button className="icon-button mobile-toggle" onClick={()=>setOpen(!open)} aria-label="Open menu">{open?<X size={18}/>:<Menu size={18}/>}</button><div className="crumb">{user?.role=== "doctor"?"Doctor workspace":"Front desk"}<span style={{color:"#c3cbc6"}}> / </span><span style={{color:"#394640"}}> {links.find(i=>path===i.href||path.startsWith(i.href+"/"))?.label??"Patients"}</span></div><div className="top-actions"><span className="subtext user-desktop">{new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"short",year:"numeric"})}</span><div className="avatar" style={{width:30,height:30}}>{user?.full_name.split(" ").map(p=>p[0]).slice(0,2).join("")??"CF"}</div></div></header><div className="content">{children}</div></main><ToastHost/></div>
}
