"use client";
import { useState, type FormEvent, type ReactNode } from "react";
import { Button, Modal } from "@/components/ui";
import { appointmentSchema, followUpSchema, patientSchema } from "@/lib/validation";
import { saveAppointment, saveFollowUp, savePatient, useClinicData } from "@/lib/store";
import { availableSlots, endTime } from "@/lib/schedule";
import { todayISO } from "@/lib/utils";
import type { Appointment, FollowUp, Patient } from "@/types";
function Item({label,children,full=false}:{label:string;children:ReactNode;full?:boolean}){return <div className={`form-item ${full?"full":""}`}><label className="label">{label}</label>{children}</div>}
function ErrorText({text}:{text?:string}){return text?<div role="alert" style={{color:"#b34f4f",fontSize:10,marginTop:4}}>{text}</div>:null}
export function PatientForm({onClose,patient}:{onClose:(saved?:boolean)=>void;patient?:Patient}){
 const [values,setValues]=useState({full_name:patient?.full_name??"",phone:patient?.phone??"",email:patient?.email??"",date_of_birth:patient?.date_of_birth??"",gender:patient?.gender??"",admin_notes:patient?.admin_notes??"",preferred_language:patient?.preferred_language??"English",preferred_channel:patient?.preferred_channel??"SMS" as "SMS"|"WhatsApp",messaging_consent:patient?.messaging_consent??false,opted_out:patient?.opted_out??false});
 const [errors,setErrors]=useState<Record<string,string>>({});const set=(key:keyof typeof values,value:string|boolean)=>setValues(v=>({...v,[key]:value}));
 const submit=(e:FormEvent)=>{e.preventDefault();const result=patientSchema.safeParse(values);if(!result.success){setErrors(result.error.flatten().fieldErrors as Record<string,string>);return}savePatient(result.data,patient?.id);onClose(true)};
 return <Modal title={patient?"Edit patient details":"Add a patient"} onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button type="submit" kind="primary" form="patient-form">Save patient</Button></>}><form id="patient-form" onSubmit={submit} className="form-grid"><Item label="Full name"><input className="field" required value={values.full_name} onChange={e=>set("full_name",e.target.value)} placeholder="Patient's name"/><ErrorText text={errors.full_name}/></Item><Item label="Phone"><input className="field" required value={values.phone} onChange={e=>set("phone",e.target.value)} placeholder="+91 98765 43210"/><ErrorText text={errors.phone}/></Item><Item label="Email"><input className="field" type="email" value={values.email} onChange={e=>set("email",e.target.value)} placeholder="name@example.com"/><ErrorText text={errors.email}/></Item><Item label="Date of birth"><input className="field" type="date" required value={values.date_of_birth} onChange={e=>set("date_of_birth",e.target.value)}/><ErrorText text={errors.date_of_birth}/></Item><Item label="Gender (optional)"><select className="select" style={{width:"100%"}} value={values.gender} onChange={e=>set("gender",e.target.value)}><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Other</option></select></Item><Item label="Preferred language"><select className="select" style={{width:"100%"}} value={values.preferred_language} onChange={e=>set("preferred_language",e.target.value)}><option>English</option><option>Hindi</option></select></Item><Item label="Preferred reminder channel"><select className="select" style={{width:"100%"}} value={values.preferred_channel} onChange={e=>set("preferred_channel",e.target.value)}><option>SMS</option><option>WhatsApp</option></select></Item><Item label="Communication consent"><label className="check-row"><input type="checkbox" checked={values.messaging_consent} onChange={e=>set("messaging_consent",e.target.checked)}/> Patient agreed to reminders</label></Item><Item label="Opt-out"><label className="check-row"><input type="checkbox" checked={values.opted_out} onChange={e=>set("opted_out",e.target.checked)}/> Do not send reminders</label></Item><Item label="Administrative notes" full><textarea className="textarea" maxLength={500} value={values.admin_notes} onChange={e=>set("admin_notes",e.target.value)} placeholder="Scheduling preferences or other administrative notes"/></Item></form></Modal>
}
export function AppointmentForm({onClose,patients,appointment,initialPatientId,initialDoctorId,initialDate,initialTime,reschedulingFrom}:{onClose:(saved?:boolean)=>void;patients:Patient[];appointment?:Appointment;initialPatientId?:string;initialDoctorId?:string;initialDate?:string;initialTime?:string;reschedulingFrom?:string}){
 const data=useClinicData();const doctors=data.doctors.filter(d=>d.active);const currentUser=data.currentUser;
 const [values,setValues]=useState({location_id:appointment?.location_id??data.locations?.[0]?.id??"",patient_id:appointment?.patient_id??initialPatientId??"",doctor_id:appointment?.doctor_id??initialDoctorId??currentUser?.doctor_id??doctors[0]?.id??"",appointment_date:appointment?.appointment_date??initialDate??todayISO(),appointment_time:appointment?.appointment_time??initialTime??"",duration_minutes:appointment?.duration_minutes??doctors.find(d=>d.id===(appointment?.doctor_id??initialDoctorId??currentUser?.doctor_id))?.appointment_duration_minutes??30,visit_type:appointment?.visit_type??"General consultation",status:appointment?.status??"Scheduled",notes:appointment?.notes??""});
 const [errors,setErrors]=useState<Record<string,string>>({});const [newPatient,setNewPatient]=useState(false);const [patientFields,setPatientFields]=useState({full_name:"",phone:"",email:""});
 const doctor=doctors.find(d=>d.id===values.doctor_id);const slots=availableSlots(doctor,values.appointment_date,data.appointments,appointment?.id??reschedulingFrom,values.duration_minutes);
 const set=(key:keyof typeof values,value:string)=>setValues(v=>({...v,[key]:value,...(key==="appointment_date"?{appointment_time:""}:{})}));
 const submit=(e:FormEvent)=>{
  e.preventDefault();const result=appointmentSchema.safeParse(values);
  if(!result.success){setErrors(result.error.flatten().fieldErrors as Record<string,string>);return}
  const selectedDoctor=doctors.find(d=>d.id===result.data.doctor_id);
  if(!selectedDoctor||!slots.includes(result.data.appointment_time)){setErrors({appointment_time:"That time is no longer available. Choose another open slot."});return}
  let patientId=result.data.patient_id;
  if(newPatient){const p=patientSchema.safeParse({full_name:patientFields.full_name,phone:patientFields.phone,email:patientFields.email,date_of_birth:"2000-01-01",gender:"",admin_notes:"",preferred_language:"English",preferred_channel:"SMS",messaging_consent:false,opted_out:false});if(!p.success){setErrors({new_patient:p.error.issues[0]?.message??"Check patient details"});return}patientId=savePatient(p.data).id}
  const source=reschedulingFrom?data.appointments.find(a=>a.id===reschedulingFrom):undefined;
  const rescheduleFields=reschedulingFrom?{rescheduled_from:reschedulingFrom,rescheduled_at:new Date().toISOString(),rescheduled_from_status:source?.status}:appointment?.rescheduled_from?{rescheduled_from:appointment.rescheduled_from,rescheduled_at:appointment.rescheduled_at,rescheduled_from_status:appointment.rescheduled_from_status}:{};
  saveAppointment({...result.data,patient_id:patientId,doctor_id:selectedDoctor.id,duration_minutes:values.duration_minutes,end_time:endTime(result.data.appointment_time,values.duration_minutes),kind:appointment?.kind??"appointment",created_by:currentUser?.id,...rescheduleFields},appointment?.id);onClose(true)
 };
 return <Modal title={reschedulingFrom?"Reschedule appointment":appointment?"Edit appointment":"Schedule an appointment"} onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button type="submit" kind="primary" form="appointment-form">{reschedulingFrom?"Confirm reschedule":"Save appointment"}</Button></>}><form id="appointment-form" className="form-grid" onSubmit={submit}>
 <Item label="Patient"><select className="select" style={{width:"100%"}} required value={newPatient?"__new__":values.patient_id} onChange={e=>{if(e.target.value==="__new__"){setNewPatient(true);set("patient_id","")}else{setNewPatient(false);set("patient_id",e.target.value)}}}><option value="">Select an existing patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}<option value="__new__">+ Create synthetic demo patient</option></select></Item>
 {newPatient&&<><Item label="New patient name"><input className="field" required value={patientFields.full_name} onChange={e=>setPatientFields(v=>({...v,full_name:e.target.value}))}/></Item><Item label="New patient phone"><input className="field" required value={patientFields.phone} onChange={e=>setPatientFields(v=>({...v,phone:e.target.value}))}/></Item><Item label="New patient email"><input className="field" type="email" value={patientFields.email} onChange={e=>setPatientFields(v=>({...v,email:e.target.value}))}/></Item><ErrorText text={errors.new_patient}/></>}
 <Item label="Clinic location"><select className="select" style={{width:"100%"}} value={values.location_id} onChange={e=>set("location_id",e.target.value)}>{(data.locations??[]).filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Item>
 <Item label="Doctor"><select className="select" style={{width:"100%"}} required value={values.doctor_id} onChange={e=>{const next=doctors.find(d=>d.id===e.target.value);setValues(v=>({...v,doctor_id:e.target.value,appointment_time:"",duration_minutes:next?.appointment_duration_minutes??30}))}}><option value="">Select a doctor</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.full_name} · {d.specialization}</option>)}</select><ErrorText text={errors.doctor_id}/></Item>
 <Item label="Date"><input className="field" type="date" min={todayISO()} required value={values.appointment_date} onChange={e=>set("appointment_date",e.target.value)}/><ErrorText text={errors.appointment_date}/></Item>
 <Item label="Duration"><select className="select" style={{width:"100%"}} value={values.duration_minutes} onChange={e=>{setValues(v=>({...v,duration_minutes:Number(e.target.value),appointment_time:""}))}}>{[15,30,45,60].map(n=><option value={n} key={n}>{n} minutes</option>)}</select></Item>
 <Item label="Available time"><select className="select" style={{width:"100%"}} required value={values.appointment_time} onChange={e=>set("appointment_time",e.target.value)}><option value="">{slots.length?"Select an available time":"No available times for this date"}</option>{slots.map(slot=><option key={slot} value={slot}>{slot}</option>)}</select><ErrorText text={errors.appointment_time}/></Item>
 <Item label="Visit type"><input className="field" required value={values.visit_type} onChange={e=>set("visit_type",e.target.value)}/><ErrorText text={errors.visit_type}/></Item>
 <Item label="Status"><select className="select" style={{width:"100%"}} value={values.status} onChange={e=>set("status",e.target.value)}>{["Scheduled","Confirmed","Completed","Cancelled","Missed"].map(s=><option key={s}>{s}</option>)}</select></Item>
 <Item label="Administrative notes" full><textarea className="textarea" maxLength={500} value={values.notes} onChange={e=>set("notes",e.target.value)} placeholder="Optional scheduling notes"/></Item></form></Modal>
}
export function FollowUpForm({onClose,patients,followUp,initialPatientId}:{onClose:(saved?:boolean)=>void;patients:Patient[];followUp?:FollowUp;initialPatientId?:string}){const [values,setValues]=useState({patient_id:followUp?.patient_id??initialPatientId??"",reason:followUp?.reason??"",due_date:followUp?.due_date??todayISO(),priority:followUp?.priority??"Medium",status:followUp?.status??"Due",assigned_to:followUp?.assigned_to??"Riya Sharma",notes:followUp?.notes??""});const [errors,setErrors]=useState<Record<string,string>>({});const set=(key:keyof typeof values,value:string)=>setValues(v=>({...v,[key]:value}));const submit=(e:FormEvent)=>{e.preventDefault();const result=followUpSchema.safeParse(values);if(!result.success){setErrors(result.error.flatten().fieldErrors as Record<string,string>);return}saveFollowUp({...result.data},followUp?.id);onClose(true)};return <Modal title={followUp?"Edit follow-up":"Create a follow-up"} onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button type="submit" kind="primary" form="followup-form">Save follow-up</Button></>}><form id="followup-form" className="form-grid" onSubmit={submit}><Item label="Patient"><select className="select" style={{width:"100%"}} required value={values.patient_id} onChange={e=>set("patient_id",e.target.value)}><option value="">Select a patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><ErrorText text={errors.patient_id}/></Item><Item label="Reason"><input className="field" required value={values.reason} onChange={e=>set("reason",e.target.value)} placeholder="Routine follow-up"/><ErrorText text={errors.reason}/></Item><Item label="Due date"><input className="field" type="date" required value={values.due_date} onChange={e=>set("due_date",e.target.value)}/><ErrorText text={errors.due_date}/></Item><Item label="Priority"><select className="select" style={{width:"100%"}} value={values.priority} onChange={e=>set("priority",e.target.value)}>{["Low","Medium","High"].map(s=><option key={s}>{s}</option>)}</select></Item><Item label="Assigned staff"><input className="field" required value={values.assigned_to} onChange={e=>set("assigned_to",e.target.value)}/></Item><Item label="Status"><select className="select" style={{width:"100%"}} value={values.status} onChange={e=>set("status",e.target.value)}>{["Due","Contacted","Booked","Declined","Unreachable","Deferred"].map(s=><option key={s}>{s}</option>)}</select></Item><Item label="Administrative notes" full><textarea className="textarea" maxLength={500} value={values.notes} onChange={e=>set("notes",e.target.value)} placeholder="Optional context for the staff member"/></Item></form></Modal>}
