"use client";
import Link from "next/link";
import { useMemo } from "react";
import { CalendarDays, Check, ChevronRight, ClipboardList, Clock3, Plus, Stethoscope } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button, PageHeader, StatusBadge } from "@/components/ui";
import { useClinicData } from "@/lib/store";
import { patientName, prettyDate, todayISO } from "@/lib/utils";
function StatLink({href,label,value,note,icon}:{href:string;label:string;value:number;note:string;icon:React.ReactNode}){return <Link href={href} className="stat-card stat-link"><div className="stat-top">{label}<div className="stat-icon">{icon}</div></div><div className="stat-value">{value}</div><div className="stat-foot">{note}</div></Link>}
export function ReceptionDashboard(){const data=useClinicData();const today=todayISO();const todayApps=data.appointments.filter(a=>a.appointment_date===today).sort((a,b)=>a.appointment_date.localeCompare(b.appointment_date)||a.appointment_time.localeCompare(b.appointment_time));const pending=data.followUps.filter(f=>(f.status==="Due"||f.status==="Pending"));const missed=data.appointments.filter(a=>a.status==="Missed"&&a.appointment_date<=today);const done=todayApps.filter(a=>a.status==="Completed");const followups=pending.slice(0,5);const chart=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const date=d.toISOString().slice(0,10);return{day:d.toLocaleDateString("en-IN",{weekday:"short"}),appointments:data.appointments.filter(a=>a.appointment_date===date).length}}),[data.appointments]);const active=data.followUps.filter(f=>["Due","Pending","Contacted","Deferred"].includes(f.status));const rate=Math.round(data.followUps.filter(f=>["Booked","Completed"].includes(f.status)).length/Math.max(active.length+data.followUps.filter(f=>["Booked","Completed"].includes(f.status)).length,1)*100);
 return <><PageHeader title={`Good morning, ${data.currentUser?.full_name.split(" ")[0]??"Riya"}`} description={`Here’s the front-desk schedule for ${data.clinic.name}.`} action={<Link href="/appointments"><Button kind="primary"><Plus size={15}/> New appointment</Button></Link>}/><div className="stat-grid"><StatLink href="/appointments?filter=today" label="Today's appointments" value={todayApps.length} note="Open today's schedule" icon={<CalendarDays size={17}/>}/><StatLink href="/follow-ups?filter=pending" label="Pending follow-ups" value={pending.length} note="Pending items across the queue" icon={<ClipboardList size={17}/>}/><StatLink href="/missed?filter=missed" label="Missed appointments" value={missed.length} note="Ready for outreach" icon={<Clock3 size={17}/>}/><StatLink href="/appointments?filter=completed-today" label="Completed today" value={done.length} note="Visits finished today" icon={<Check size={17}/>}/></div>
 <div className="card"><div className="card-head"><div><div className="card-title">Today’s appointments</div><div className="card-subtitle">{prettyDate(today,"EEEE, MMM d")} · {todayApps.length} visits, earliest first</div></div><Link href="/appointments?filter=today" className="btn btn-quiet btn-sm">View schedule <ChevronRight size={14}/></Link></div><div className="table-wrap">{todayApps.length?<table className="table"><thead><tr><th>TIME</th><th>PATIENT</th><th>PHONE</th><th>DOCTOR</th><th>VISIT TYPE</th><th>STATUS</th></tr></thead><tbody>{todayApps.map(a=>{const p=data.patients.find(x=>x.id===a.patient_id);const doctor=data.doctors.find(d=>d.id===a.doctor_id);return <tr key={a.id}><td>{a.appointment_time}</td><td><Link href={`/patients/${a.patient_id}`} className="person"><div className="avatar">{p?.full_name.split(" ").map(s=>s[0]).join("")}</div><strong>{p?.full_name}</strong></Link></td><td>{p?.phone}</td><td>{doctor?.full_name??"—"}</td><td>{a.visit_type}</td><td><StatusBadge status={a.status}/></td></tr>})}</tbody></table>:<div className="empty"><strong>No appointments today</strong><p>The clinic schedule is clear for today.</p><Link href="/appointments"><Button kind="primary">Schedule a visit</Button></Link></div>}</div></div>
 <div className="dashboard-grid"><section className="card"><div className="card-head"><div><div className="card-title">Pending follow-ups</div><div className="card-subtitle">{pending.length} tasks need attention</div></div><Link href="/follow-ups?filter=pending" className="btn btn-quiet btn-sm">View queue <ChevronRight size={14}/></Link></div>{followups.length?<div style={{padding:"2px 18px"}}>{followups.map(f=><div className="metric-line" key={f.id}><div><Link href={`/patients/${f.patient_id}`} style={{fontWeight:650,color:"#3e4a44"}}>{patientName(data.patients,f.patient_id)}</Link><div className="subtext">{f.reason} · Due {prettyDate(f.due_date,"MMM d")}</div></div><StatusBadge status={f.priority}/></div>)}</div>:<div className="empty"><strong>No pending follow-ups</strong><p>There are no pending outreach tasks.</p></div>}</section><section className="card"><div className="card-head"><div><div className="card-title">Appointments this week</div><div className="card-subtitle">Last 7 days across the clinic</div></div><Stethoscope size={17} color="#718078"/></div><div style={{height:190,padding:"16px 8px 8px"}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:5,right:10,bottom:0,left:-18}}><CartesianGrid stroke="#edf1ee" vertical={false}/><XAxis dataKey="day" tick={{fontSize:10,fill:"#87928c"}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:10,fill:"#87928c"}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:8,fontSize:11,border:"1px solid #e6ebe8"}}/><Line type="monotone" dataKey="appointments" stroke="#338163" strokeWidth={2.5} dot={{r:3,fill:"#338163"}}/></LineChart></ResponsiveContainer></div><div style={{padding:"0 20px 17px",borderTop:"1px solid #eef1ef",display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:2}}><div style={{fontSize:11,color:"#7f8a84",paddingTop:14}}>Follow-up completion rate</div><div className="rate" style={{paddingTop:8}}>{rate}%</div></div></section></div></>}
