"use client";
import { useEffect, useState, type ReactNode } from "react";
import { X, Search as SearchIcon, Inbox } from "lucide-react";
import type { AppointmentStatus, FollowUpStatus, Priority } from "@/types";
export function PageHeader({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="page-header"><div><h1>{title}</h1><p>{description}</p></div>{action}</div>}
export function Button({children,onClick,kind="default",className="",type="button",form}:{children:ReactNode;onClick?:()=>void;kind?:"default"|"primary"|"quiet"|"danger";className?:string;type?:"button"|"submit";form?:string}){return <button type={type} form={form} onClick={onClick} className={`btn ${kind==="primary"?"btn-primary":kind==="quiet"?"btn-quiet":kind==="danger"?"btn-danger":""} ${className}`}>{children}</button>}
export function StatusBadge({status}:{status:AppointmentStatus|FollowUpStatus|Priority|string}){return <span className={`status ${status.toLowerCase()}`}>{status}</span>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty"><div className="empty-icon"><Inbox size={20}/></div><strong>{title}</strong><p>{description}</p>{action}</div>}
export function SearchBox({value,onChange,placeholder="Search..."}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search"><SearchIcon size={15}/><input className="field" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="btn btn-quiet btn-sm" onClick={onClose} aria-label="Close"><X size={17}/></button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-foot">{footer}</div>}</div></div>}
export function ToastHost(){const [message,setMessage]=useState("");useEffect(()=>{const show=(event:Event)=>{const custom=event as CustomEvent<string>;setMessage(custom.detail);window.setTimeout(()=>setMessage(""),2800)};window.addEventListener("clinicflow:toast",show);return()=>window.removeEventListener("clinicflow:toast",show)},[]);return message?<div className="toast">✓ &nbsp;{message}</div>:null}
export function toast(message:string){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("clinicflow:toast",{detail:message}))}
