"use client";
import Link from "next/link";
import { useState } from "react";
import { Check, CalendarPlus, X } from "lucide-react";
import { AppointmentForm } from "@/components/forms";
import { EmptyState, PageHeader, StatusBadge, toast } from "@/components/ui";
import { useClinicData, updateAppointment } from "@/lib/store";
import { patientName, todayISO } from "@/lib/utils";
import type { AppointmentStatus } from "@/types";
export default function DoctorSchedule(){const data=useClinicData();const [date,setDate]=useState(todayISO());const [selected,setSelected]=useState<string|undefined>();const doctorId=data.currentUser?.doctor_id;const rows=data.appointments.filter(a=>a.doctor_id===doctorId&&a.appointment_date===date).sort((a,b)=>a.appointment_time.localeCompare(b.appointment_time));const update=(id:string,status:AppointmentStatus)=>{updateAppointment(id,{status});toast(`Appointment marked ${status.toLowerCase()}`)};const rescheduled=selected?data.appointments.find(a=>a.id===selected):undefined;return <><PageHeader title="My schedule" description="Your appointments, patient details and visit actions."/>{doctorId&&<div className="card"><div className="toolbar"><label className="label" style={{margin:0}}>Date</label><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/><span className="subtext">{rows.length} appointments</span></div>{rows.length?<div className="table-wrap"><table className="table"><thead><tr><th>TIME</th><th>PATIENT</th><th>CONTACT</th><th>VISIT TYPE</th><th>STATUS</th><th>QUEUE</th><th>NOTES</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(a=>{const patient=data.patients.find(p=>p.id===a.patient_id);return <tr key={a.id}><td>{a.appointment_time}–{a.end_time}</td><td><Link href={`/patients/${a.patient_id}`} style={{fontWeight:650}}>{patientName(data.patients,a.patient_id)}</Link></td><td><a href={`tel:${patient?.phone}`} className="contact-link">{patient?.phone}</a><div className="subtext"><a href={`mailto:${patient?.email}`}>{patient?.email}</a></div></td><td>{a.visit_type}</td><td><StatusBadge status={a.status}/>{a.rescheduled_from&&<div className="subtext" style={{color:"#327b5d"}}>Rescheduled</div>}</td><td>{a.queue_status?<>#{a.queue_token} · {a.queue_status.replaceAll("_"," ")}</>:"Not arrived"}</td><td>{a.notes||"—"}</td><td><div style={{display:"flex",gap:3}}><button className="btn btn-quiet btn-sm" title="Mark completed" onClick={()=>update(a.id,"Completed")}><Check size={14}/></button><button className="btn btn-quiet btn-sm" title="Mark missed" onClick={()=>update(a.id,"Missed")}><X size={14}/></button><button className="btn btn-quiet btn-sm" title="Reschedule" onClick={()=>setSelected(a.id)}><CalendarPlus size={14}/></button><Link className="btn btn-quiet btn-sm" href={`/patients/${a.patient_id}`}>Patient</Link></div></td></tr>})}</tbody></table></div>:<EmptyState title="No appointments on this date" description="Pick another day to see your clinic schedule."/>}</div>}{rescheduled&&<AppointmentForm patients={data.patients} initialPatientId={rescheduled.patient_id} initialDoctorId={rescheduled.doctor_id} reschedulingFrom={rescheduled.id} onClose={saved=>{if(saved){updateAppointment(rescheduled.id,{status:"Cancelled"});toast("Appointment rescheduled")}setSelected(undefined)}}/>}</>}
