import type { Appointment, ClinicData, Doctor, FollowUp, Patient, StaffUser } from "@/types";
const today = new Date();
const day = (offset:number) => { const d=new Date(today); d.setDate(d.getDate()+offset); return d.toISOString().slice(0,10); };
const created = new Date().toISOString();
const people: Array<[string,string,string,string]> = [
 ["Aarav Mehta","+91 98765 41021","aarav.mehta@example.com","1991-04-12"],["Priya Nair","+91 98210 73654","priya.nair@example.com","1985-11-03"],["Kabir Shah","+91 99870 12468","kabir.shah@example.com","1978-06-21"],["Ananya Iyer","+91 98190 56231","ananya.iyer@example.com","1998-02-14"],["Rohan Desai","+91 97690 38142","rohan.desai@example.com","1969-09-08"],["Meera Joshi","+91 98920 64713","meera.joshi@example.com","2001-12-19"],["Ishaan Kapoor","+91 98203 51980","ishaan.kapoor@example.com","1989-01-26"],["Diya Menon","+91 98197 24860","diya.menon@example.com","1994-07-17"],["Arjun Rao","+91 98702 83514","arjun.rao@example.com","1973-05-30"],["Sara Khan","+91 99204 17326","sara.khan@example.com","1996-10-02"],["Neel Kulkarni","+91 98195 34062","neel.kulkarni@example.com","1982-03-23"],["Tara Fernandes","+91 98330 72146","tara.fernandes@example.com","1990-08-09"],["Vivaan Patel","+91 98218 90635","vivaan.patel@example.com","2003-12-01"],["Aditi Sinha","+91 98704 51827","aditi.sinha@example.com","1977-01-16"],["Dev Malhotra","+91 98193 46270","dev.malhotra@example.com","1987-06-04"],["Nisha Pillai","+91 98201 87453","nisha.pillai@example.com","1999-09-27"],["Om Prakash","+91 98670 29318","om.prakash@example.com","1965-11-11"],["Leela Thomas","+91 98922 60547","leela.thomas@example.com","1993-03-06"]
];
export const demoPatients:Patient[] = people.map((p,i)=>({id:`patient-${i+1}`,full_name:p[0],phone:p[1],email:p[2],date_of_birth:p[3],gender:i%2?"Female":"Male",admin_notes:i===0?"Prefers morning appointments.":"",preferred_language:i%4===0?"Hindi":"English",preferred_channel:i%2?"WhatsApp":"SMS",messaging_consent:i%5!==0,opted_out:i===16,created_at:created,updated_at:created}));
export const demoDoctors:Doctor[]=[
 {id:"doctor-1",profile_id:"profile-doctor-1",full_name:"Dr. Ananya Rao",email:"doctor@clinicflow.demo",specialization:"Dermatology",active:true,working_days:[1,2,3,4,5],start_time:"09:00",end_time:"14:00",appointment_duration_minutes:30,unavailable_dates:[]},
 {id:"doctor-2",profile_id:"profile-doctor-2",full_name:"Dr. Meera Shah",email:"meera@clinicflow.demo",specialization:"General Medicine",active:true,working_days:[1,2,3,4,5,6],start_time:"10:00",end_time:"18:00",appointment_duration_minutes:30,unavailable_dates:[]},
 {id:"doctor-3",profile_id:"profile-doctor-3",full_name:"Dr. Kavya Nair",email:"kavya@clinicflow.demo",specialization:"Pediatrics",active:true,working_days:[2,3,4,5,6],start_time:"09:00",end_time:"16:00",appointment_duration_minutes:30,unavailable_dates:[]}
];
export const demoStaff:StaffUser[]=[{id:"staff-reception-1",full_name:"Riya Sharma",email:"reception@clinicflow.demo",role:"receptionist",active:true,clinic_id:"clinic-demo"}];
const types=["General consultation","Routine visit","Review visit","Wellness visit","New patient visit"];
const statusByToday=["Confirmed","Scheduled","Completed","Confirmed","Missed","Scheduled","Completed","Scheduled"] as const;
const pastOffsets=[-1,-2,-3,-4,-5,-6];
export const demoAppointments:Appointment[]=Array.from({length:28},(_,i)=>{
 const isToday=i<8;const d=isToday?0:i<14?pastOffsets[i-8]:i-13;const doctor=demoDoctors[i%3];
 const slot=isToday?Math.floor(i/3):i%8;const [baseHour,baseMinute]=doctor.start_time.split(":").map(Number);const startMinutes=baseHour*60+baseMinute+slot*30;const hour=Math.floor(startMinutes/60);const minute=startMinutes%60;
 const time=`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}`;
 const status=isToday?statusByToday[i]:i===14?"Missed":i===21?"Cancelled":i%6===0?"Completed":"Scheduled";
 return{id:`appointment-${i+1}`,patient_id:i===20?demoPatients[9].id:demoPatients[i%demoPatients.length].id,doctor_id:i===20?demoDoctors[0].id:doctor.id,appointment_date:day(d),appointment_time:time,end_time:`${String(hour+(minute===30?1:0)).padStart(2,"0")}:${String(minute===30?0:30).padStart(2,"0")}`,duration_minutes:30,visit_type:types[i%types.length],status:i===9||i===12?"Missed":status,notes:"",kind:"appointment",...(isToday&&i<2?{queue_status:i===0?"waiting":"called",queue_token:i+1,checked_in_at:new Date(Date.now()-i*600000).toISOString()}:{}) ,created_at:created,updated_at:created,...(i===20?{rescheduled_from:"appointment-10",rescheduled_at:created}:{})};
});
demoAppointments.push({id:"appointment-walkin-1",patient_id:demoPatients[17].id,doctor_id:"doctor-2",appointment_date:day(0),appointment_time:"11:15",end_time:"11:45",duration_minutes:30,visit_type:"Walk-in visit",status:"Scheduled",kind:"walk-in",queue_status:"waiting",queue_token:3,checked_in_at:new Date().toISOString(),notes:"",created_at:created,updated_at:created});
const reasons=["Routine check-in","Post-visit follow-up","Appointment rescheduling","Wellness visit reminder","Patient requested callback","Review visit coordination","Missed appointment outreach","Confirm next visit","Follow-up call","Appointment confirmation","Routine follow-up","Scheduling request"];
export const demoFollowUps:FollowUp[]=Array.from({length:14},(_,i)=>({id:`followup-${i+1}`,patient_id:demoPatients[(i*3+1)%demoPatients.length].id,appointment_id:demoAppointments[i]?.id,reason:reasons[i],due_date:day([0,-2,1,3,-1,0,5,2,-4,7,0,4,1,10][i]),priority:(i%5===0?"High":i%3===0?"Low":"Medium") as FollowUp["priority"],status:(i===2?"Booked":i===8?"Completed":i===5?"Contacted":i===7?"Unreachable":i===10?"Deferred":i===12?"Declined":"Due") as FollowUp["status"],assigned_to:"Riya Sharma",notes:"",last_contacted_at:i===5?created:undefined,created_at:created,updated_at:created}));
export const initialData:ClinicData={patients:demoPatients,appointments:demoAppointments,followUps:demoFollowUps,doctors:demoDoctors,staff:demoStaff,clinic:{name:"ClinicFlow Demo Clinic",email:"hello@clinicflow.demo",phone:"+91 22 4890 2100",duration:30},currentUser:{id:"staff-reception-1",full_name:"Riya Sharma",email:"reception@clinicflow.demo",role:"receptionist"},activity:[{id:"activity-seed-1",patient_id:"patient-1",appointment_id:"appointment-1",actor:"Riya Sharma",action:"Patient checked in",detail:"Queue token #1",created_at:created},{id:"activity-seed-2",patient_id:"patient-18",appointment_id:"appointment-walkin-1",actor:"Riya Sharma",action:"Walk-in checked in",detail:"Queue token #3",created_at:created}],waitlist:[{id:"waitlist-1",patient_id:"patient-3",doctor_id:"doctor-2",preferred_date:day(8),status:"Waiting",created_at:created,updated_at:created}],communicationLog:[],reminderTemplates:[{id:"reminder-en",name:"Appointment reminder",language:"English",body:"Hello {{name}}, this is a reminder of your appointment at {{clinic}} on {{date}} at {{time}}. Reply to the clinic if you need to make a change.",active:true},{id:"reminder-hi",name:"Appointment reminder",language:"Hindi",body:"नमस्ते {{name}}, {{date}} को {{time}} बजे {{clinic}} में आपकी अपॉइंटमेंट है। बदलाव के लिए क्लिनिक से संपर्क करें।",active:true}],locations:[{id:"location-main",name:"Main Clinic",address:"12 Lake Road",active:true},{id:"location-north",name:"North Clinic",address:"4 Market Street",active:true}]};
