"use client";
import { useSyncExternalStore } from "react";
import { initialData } from "@/lib/demo-data";
import type { Appointment, ClinicActivity, ClinicData, CommunicationLog, CurrentUser, Doctor, FollowUp, Patient, ReminderTemplate, StaffUser, WaitlistEntry } from "@/types";
import { demoMode } from "@/lib/supabase";
import { persistClinicDataToSupabase } from "@/services/data";
const KEY="clinicflow-demo-v1";
let data:ClinicData=initialData;
let ready=false;
let cloudClinicId:string|undefined;
let cloudWriteQueue:Promise<void>=Promise.resolve();
const listeners=new Set<()=>void>();
function emit(){listeners.forEach(fn=>fn())}
function initialize(){if(ready)return;ready=true;try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Partial<ClinicData>;data={...initialData,...parsed,activity:parsed.activity??[],waitlist:parsed.waitlist??[],communicationLog:parsed.communicationLog??[],reminderTemplates:parsed.reminderTemplates??initialData.reminderTemplates,locations:parsed.locations??initialData.locations,doctors:parsed.doctors??initialData.doctors,staff:parsed.staff??initialData.staff,appointments:(parsed.appointments??initialData.appointments).map((a,i)=>({...a,doctor_id:a.doctor_id??initialData.doctors[i%initialData.doctors.length]?.id,end_time:a.end_time??"09:30",kind:a.kind??"appointment"})),followUps:(parsed.followUps??initialData.followUps).map(f=>({...f,status:f.status==="Pending"?"Due":f.status}))}}else localStorage.setItem(KEY,JSON.stringify(data))}catch{data=initialData} }
function persist(){if(typeof window!=="undefined"){if(demoMode)localStorage.setItem(KEY,JSON.stringify(data));else if(cloudClinicId){const snapshot=data;const clinicId=cloudClinicId;cloudWriteQueue=cloudWriteQueue.then(()=>persistClinicDataToSupabase(snapshot,clinicId)).catch(error=>{window.dispatchEvent(new CustomEvent("clinicflow:toast",{detail:error instanceof Error?`Save failed: ${error.message}`:"Save failed"}))})}emit()}}
export function loadData(value:ClinicData,clinicId?:string){data=value;cloudClinicId=clinicId;ready=true;emit()}
export function getData(){initialize();return data}
function subscribe(fn:()=>void){listeners.add(fn);return()=>listeners.delete(fn)}
export function useClinicData(){return useSyncExternalStore(subscribe,()=>getData(),()=>initialData)}
export function makeId(prefix:string){return demoMode?`${prefix}-${Math.random().toString(36).slice(2,10)}`:crypto.randomUUID()}
export function addActivity(action:string,detail:string,patient_id?:string,appointment_id?:string,follow_up_id?:string){initialize();const event:ClinicActivity={id:makeId("activity"),actor:data.currentUser?.full_name??"Clinic staff",action,detail,patient_id,appointment_id,follow_up_id,created_at:new Date().toISOString()};data={...data,activity:[event,...(data.activity??[])]};persist();return event}
export function savePatient(input:Omit<Patient,"id"|"created_at"|"updated_at">,id?:string){initialize();const now=new Date().toISOString();const old=data.patients.find(p=>p.id===id);const patient:Patient={...input,id:id??makeId("patient"),created_at:old?.created_at??now,updated_at:now};data={...data,patients:id?data.patients.map(p=>p.id===id?patient:p):[patient,...data.patients]};addActivity(id?"Patient updated":"Patient added",patient.full_name,patient.id);persist();return patient}
export function saveAppointment(input:Omit<Appointment,"id"|"created_at"|"updated_at">,id?:string){initialize();const now=new Date().toISOString();const old=data.appointments.find(a=>a.id===id);const ap:Appointment={...input,id:id??makeId("appointment"),created_at:old?.created_at??now,updated_at:now};data={...data,appointments:id?data.appointments.map(a=>a.id===id?ap:a):[ap,...data.appointments]};addActivity(id?"Appointment updated":"Appointment booked",`${ap.appointment_date} ${ap.appointment_time}`,ap.patient_id,ap.id);persist();return ap}
export function updateAppointment(id:string,patch:Partial<Appointment>){initialize();const old=data.appointments.find(a=>a.id===id);data={...data,appointments:data.appointments.map(a=>a.id===id?{...a,...patch,updated_at:new Date().toISOString()}:a)};if(old)addActivity("Appointment changed",patch.status?`Status: ${patch.status}`:patch.queue_status?`Queue: ${patch.queue_status}`:"Schedule details updated",old.patient_id,id);persist()}
export function saveFollowUp(input:Omit<FollowUp,"id"|"created_at"|"updated_at">,id?:string){initialize();const now=new Date().toISOString();const old=data.followUps.find(f=>f.id===id);const item:FollowUp={...input,id:id??makeId("followup"),created_at:old?.created_at??now,updated_at:now};data={...data,followUps:id?data.followUps.map(f=>f.id===id?item:f):[item,...data.followUps]};addActivity(id?"Follow-up updated":"Follow-up created",item.reason,item.patient_id,undefined,item.id);persist();return item}
export function updateFollowUp(id:string,patch:Partial<FollowUp>){initialize();const old=data.followUps.find(f=>f.id===id);data={...data,followUps:data.followUps.map(f=>f.id===id?{...f,...patch,updated_at:new Date().toISOString()}:f)};if(old)addActivity("Follow-up changed",patch.status?`Outcome: ${patch.status}`:"Follow-up details updated",old.patient_id,undefined,id);persist()}
export function updateClinic(patch:Partial<ClinicData["clinic"]>){initialize();data={...data,clinic:{...data.clinic,...patch}};addActivity("Clinic settings updated","Clinic profile changed");persist()}
export function setCurrentUser(user:CurrentUser|undefined){initialize();data={...data,currentUser:user};emit()}
export function saveDoctor(doctor:Doctor){initialize();const exists=data.doctors.some(d=>d.id===doctor.id);data={...data,doctors:exists?data.doctors.map(d=>d.id===doctor.id?doctor:d):[...data.doctors,doctor]};addActivity(exists?"Doctor profile updated":"Doctor profile added",doctor.full_name);persist()}
export function saveStaff(staff:StaffUser){initialize();data={...data,staff:data.staff.some(s=>s.id===staff.id)?data.staff.map(s=>s.id===staff.id?staff:s):[staff,...data.staff]};addActivity("Receptionist access changed",`${staff.full_name} · ${staff.active?"active":"inactive"}`);persist()}
export function saveLocations(locations:NonNullable<ClinicData["locations"]>){initialize();data={...data,locations};addActivity("Clinic locations updated",`${locations.length} locations`);persist()}
export function saveWaitlistEntry(entry:WaitlistEntry){initialize();data={...data,waitlist:[entry,...(data.waitlist??[])]};addActivity("Waitlist updated",entry.status,entry.patient_id);persist()}
export function updateWaitlistEntry(id:string,patch:Partial<WaitlistEntry>){initialize();const old=data.waitlist?.find(e=>e.id===id);data={...data,waitlist:(data.waitlist??[]).map(e=>e.id===id?{...e,...patch,updated_at:new Date().toISOString()}:e)};if(old)addActivity("Waitlist entry updated",patch.status??"Entry changed",old.patient_id,patch.offered_appointment_id);persist()}
export function logCommunication(entry:CommunicationLog){initialize();data={...data,communicationLog:[entry,...(data.communicationLog??[])]};addActivity("Reminder simulated",entry.result==="Blocked"?`Blocked: ${entry.reason}`:`${entry.channel} · ${entry.language}`,entry.patient_id);persist()}
export function saveReminderTemplate(template:ReminderTemplate){initialize();data={...data,reminderTemplates:[...(data.reminderTemplates??[]).filter(t=>t.id!==template.id),template]};persist()}
export function resetDemo(){data=initialData;ready=true;persist()}
