"use client";
import Link from "next/link";
import { CalendarDays, Check, ChevronRight, ClipboardList, Clock3 } from "lucide-react";
import { Button, EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { useClinicData } from "@/lib/store";
import { patientName, prettyDate, todayISO } from "@/lib/utils";
export default function DoctorDashboard(){const data=useClinicData();const doctor=data.doctors.find(d=>d.id===data.currentUser?.doctor_id);const today=todayISO();const appointments=data.appointments.filter(a=>a.doctor_id===doctor?.id&&a.appointment_date===today).sort((a,b)=>a.appointment_date.localeCompare(b.appointment_date)||a.appointment_time.localeCompare(b.appointment_time));const future=data.appointments.filter(a=>a.doctor_id===doctor?.id&&a.appointment_date>today&&!["Cancelled","Missed"].includes(a.status)).sort((a,b)=>a.appointment_date.localeCompare(b.appointment_date)||a.appointment_time.localeCompare(b.appointment_time)).slice(0,4);const patientIds=new Set(data.appointments.filter(a=>a.doctor_id===doctor?.id).map(a=>a.patient_id));const pending=data.followUps.filter(f=>patientIds.has(f.patient_id)&&(f.status==="Due"||f.status==="Pending"));const missed=data.appointments.filter(a=>a.doctor_id===doctor?.id&&a.status==="Missed"&&a.appointment_date<=today);
 return <><PageHeader title={`Good morning, ${doctor?.full_name.replace("Dr. ","")??"Doctor"}`} description={`${doctor?.specialization??"Clinic"} · Your schedule for ${prettyDate(today,"EEEE, MMM d")}.`} action={<Link href="/doctor/schedule"><Button kind="primary"><CalendarDays size={15}/> My schedule</Button></Link>}/><div className="stat-grid"><DoctorStat href="/doctor/schedule" label="Today's appointments" value={appointments.length} note="Your schedule today" icon={<CalendarDays size={17}/>}/><DoctorStat href="/follow-ups?filter=pending" label="Pending follow-ups" value={pending.length} note="For your patients" icon={<ClipboardList size={17}/>}/><DoctorStat href="/missed?filter=missed" label="Missed appointments" value={missed.length} note="Your patients" icon={<Clock3 size={17}/>}/><DoctorStat href="/appointments?filter=completed-today" label="Completed today" value={appointments.filter(a=>a.status==="Completed").length} note="Visits finished" icon={<Check size={17}/>}/></div><div className="dashboard-grid"><section className="card"><div className="card-head"><div><div className="card-title">Today’s appointments</div><div className="card-subtitle">{appointments.length} visits · sorted by time</div></div><Link href="/doctor/schedule" className="btn btn-quiet btn-sm">Full schedule <ChevronRight size={14}/></Link></div>{appointments.length?<table className="table"><thead><tr><th>TIME</th><th>PATIENT</th><th>VISIT</th><th>STATUS</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{a.appointment_time}</td><td><Link href={`/patients/${a.patient_id}`} style={{fontWeight:650}}>{patientName(data.patients,a.patient_id)}</Link></td><td>{a.visit_type}</td><td><StatusBadge status={a.status}/></td></tr>)}</tbody></table>:<EmptyState title="No appointments today" description="Your schedule is clear for today."/>}</section><section className="card"><div className="card-head"><div><div className="card-title">Upcoming visits</div><div className="card-subtitle">Next scheduled patients</div></div></div>{future.length?<div style={{padding:"0 18px"}}>{future.map(a=><div className="metric-line" key={a.id}><div><Link href={`/patients/${a.patient_id}`} style={{fontWeight:650}}>{patientName(data.patients,a.patient_id)}</Link><div className="subtext">{prettyDate(a.appointment_date,"MMM d")} · {a.appointment_time}</div></div><StatusBadge status={a.status}/></div>)}</div>:<EmptyState title="No upcoming visits" description="New bookings will appear here."/>}</section></div></>}
function DoctorStat({href,label,value,note,icon}:{href:string;label:string;value:number;note:string;icon:React.ReactNode}){return <Link href={href} className="stat-card stat-link"><div className="stat-top">{label}<div className="stat-icon">{icon}</div></div><div className="stat-value">{value}</div><div className="stat-foot">{note}</div></Link>}
